$(function(){
$('.open').click(function(){
    $('.gnb').stop().slideDown();
    $('.open').hide();
    $('.close').show();
})
$('.close').click(function(){
    $('.gnb').stop().slideUp();
    $('.open').show();
    $('.close').hide();
})
});